Reveal-IQ/MEMS

client/src/components/Asset/AdditionalInformation.vue, client/src/components/Asset/EquipmentAcquisition.vue, client/src/components/Asset/EquipmentLocation.vue, client/src/components/Asset/GeneralInformation.vue, client/src/components/Asset/MaintenanceAndSupport.vue, client/src/components/Asset/MultipleEquipmentEntry.vue, client/src/views/Asset/Asset.vue
Asset Page Designed
- All Sections are components and imported into the main `Asset.vue` component.
- I changed a select input to checkbox in the `MaintenanceAndSupport.vue` component to properly describe the user and techincal manual available. It can however be reverted to being select input as the Figma Design is.
- `ButtonComponent` created in the initial branch was not available in this branch so I commented out those portions and used a plain button insertion.
=> Edd alpha asset

src/client/web/src/App.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-AdditionalInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-EquipmentAcquisition.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-EquipmentLocation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-GeneralInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-MaintenanceAndSupport.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-MultipleEquipmentEntry.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-Btn.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY-FacilityInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FormHeader.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-Input.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-Landing.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MANUFACTURER/MANUFACTURER-ManufacturerInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MANUFACTURER/MANUFACTURER.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL-ModelDescription.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL-VendorSupport.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-Section.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-CustomerService.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-VendorInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD.vue, src/client/web/src/components/BIOMD/BIOMD/Style/BIOMD.scss, src/client/web/src/components/BIOMD/BIOMD/Style/font-style.scss, src/client/web/src/components/CORE/SCFLD/NAVIG/NAVIG.vue, src/client/web/src/components/CORE/STPWZ/STPWZ-InstituteInfo.vue, src/client/web/src/components/GLOBAL/Styles/font-style.scss, src/client/web/vue.config.js
All `Styles` Applied and `Reusable Components` Created for `Buttons`, `Section`, `Inputs` and `Headings`
=> Apply styles rc01 biomd UI

src/api/api/BIOMD/BIOMD.js, src/devop/docker-compose.yml
Added API Create Records functionality to BIOMD.
The CREATE_RECORD API will provide the following functionality:
1. Create Vendor Record
2. Create Manufacturer Record
3. Create Facility Record
4. Create Model Record
5. Create Asset Record
This API will support the feature to save user inputted data from the front-end UI.
The API Test tool was used to test the creation of different records.
- [ Test Scenario YAML](https://1drv.ms/u/s!Aoyt_5MLLrQsi8M_8bbkKjWy7vpX8g?e=1wNxyA)
- [API Report conducted on 10/20/22](https://1drv.ms/b/s!Aoyt_5MLLrQsi8kvgiZW4RWaX-Ysog?e=7pF1BY)
=> BIOMD Create Records API

src/api/api/BIOMD/BIOMD.js
The FIND_RECORD api provides the ability to search and retrieve records from the DB. 
#23 Pending
This API allow for the UI to display content from the DB.
The API testing report can be found [here](https://1drv.ms/b/s!Aoyt_5MLLrQsi8oYMaH2m2rzAOMPfA?e=vTa6b1). This used the following [YAML File](https://1drv.ms/u/s!Aoyt_5MLLrQsi8oZ_v2FIGrPYQ6rRg?e=IbIc9s) to test.
=> BIOMD API - Find_Record V0.1.0

README.md, src/api/api/BIOMD/BIOMD.js
=> Rebase to get features from dev-v010

src/README.md
=> Readme Installation Instruction Updates

new_story_template.md
Adding a new template for new story / feature
It will allow the team with some predefined steps to help them draw out the feature or story better
RC08-01 from the Sprint plan 09
To help the team with a new story/feature template
using VSC preview
no applicable
=> new story template

src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY-FacilityInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MANUFACTURER/MANUFACTURER-ManufacturerInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MANUFACTURER/MANUFACTURER.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-VendorInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue
Select Demographic Location
Select the Country which fetches corresponding States which in turn fetches Corresponding Districts
=> 36 38 select demographic location

src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ManufacturerInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ModelInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue
Manufacturer Information and Model Information Added to New Vendor Page
Add Manufacturer and Model Buttons linked to New Manufacturer and Model Pages
=> 44 add manufacturer model to vendor

README.md
This change updates the release management and branching strategies used for this project
#64 
This change is proposed as an alternative to the current approach which switches the current development branch based on the most recent release cut.
=> [64] Update README with new Release Management

src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-EquipmentAcquisition.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-EquipmentLocation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-GeneralInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL-ModelDescription.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue
Select fields in Asset Registration
API integration for All select fields
=> [53] - Select Fields

src/client/web/src/store/modules/fetchAPI.js, src/client/web/src/store/modules/socketLink.js, src/client/web/vue.config.js
The Host files have been changed to support connections to mems.revealfoundation.com
=> API Host connection changed for MEMS

src/api/api/BIOMD/BIOMD.js, src/api/docs/BIOMD_API.md, src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-Landing.vue
The dashboard has been updated with tables to display Asset and Vendor records.
=> [84] Dashboard Updates

src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MANUFACTURER/MANUFACTURER.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-Landing.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-SuccessPage.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD.vue
Success Page Design and Integration
=> [43] success page integration

src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-Btn2.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-CustomerService.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ManufacturerInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ModelInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-NewManufacturer.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-VendorInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue
Vendor Page Update
Vendor Page updated according to new UI guide on Figma
- Fields aligned vertically
- Create a new Manufacturer 
- Assign Model(s)
- View all assigned Model(s)
=> Vendor Page Update

src/api/api/BIOMD/BIOMD.js
Add backend support to create Department records
#96 
Needed to create Department records from  the client.
=> [96] Add Department Record Creation

src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-CustomerService.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ManufacturerInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ModelInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-NewManufacturer.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue
Bug Fix on the Vendor Form
- #88 
- #89 
- #90 
- #91
=> Vendor UI Bug Fix

src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-Toast.vue
=> Feature/create UI toast

src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-AssetDetails.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ManufacturerInfo.vue
=> bugfix-find-model-op

src/client/web/src/store/modules/recordSchema.js, src/client/web/src/store/modules/recordSchema.test.js
Create record schema for Department.
#116 
Needed for dashboard feature.
See recordSchema unit test.
=> [116] Department Record Schema Support in Client

src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-AssetDetails.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-AssetLocation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD-AssetDetail.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD-Model.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY-FacilityInformation.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL-ModelDescription.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD.vue, src/client/web/src/store/modules/recordSchema.js
- List all Models in inventory
- List all Assets according to the Model
- Asset Profile according to the Selected Asset
All Models Listed
List all Assets within Model
Asset Profile
No asset assigned to Model
=> [100] Site Dashboard Overview [API]

src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ManufacturerInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-ModelInfo.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR-NewManufacturer.vue
#123 
- Model and Manufacturer Data List updates in real time
=> [123][VENDOR]Bugfix/update data list after created

src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-AssetDetails.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD-AssetDetail.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD-Model.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD.vue, src/client/web/src/store/modules/recordSchema.js
Parent Asset API integrated
- API integrated in Dashboard Asset Profile
- API integrated in Asset Detail Form
- Select Parent Asset Equipment Number to show Selected Asset Profile
=> Feature/Integrate Parent Asset API

src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD-ManufacturerProfile.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD-Model.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-ToastGlobal.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD.vue
Manufacturer List on the dashboard view with Manufacturer Profile
=> v0.1.1 - Feature/ManufacturerProfile

src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY-SiteDescription.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD.vue
=> v0.1.1 - Site Description Created

src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET-PurchaseDetails.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-ASSET/ASSET.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD.vue, src/client/web/src/store/modules/recordSchema.js
=> v0.1.2 - Purchase Cost Added to Asset Detail

src/client/web/src/components/BIOMD/BIOMD/BIOMD-DASHBOARD/DASHBOARD.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-REPORTS/REPORTS-AnnualInflow.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-REPORTS/REPORTS-Functionality.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-REPORTS/REPORTS-List.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-REPORTS/REPORTS-Summary1.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-REPORTS/REPORTS-Summary2.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-REPORTS/REPORTS.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-ReportList.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD-UI/UI-StatCard.vue, src/client/web/src/components/BIOMD/BIOMD/BIOMD.vue
=> v0.2 - Reports ui created

src/api/api/BIOMD/BIOMD.js
=> GET_REPORTS API references new UMDNS collection
